### ISSUE TITLE
Documentation about requirements for the source image filename is missing and specific errors from getDiskData() are replaced with a generic one

### ISSUE THREAD

**Issue by varesa** [carlmontanari/boxen#48]
I spent a fair bit of time trying to get past errors looking like this:
```
$ boxen package --disk ~/Downloads/PA-VM-KVM-10.2.9-h1.qcow2
      info   1730818372 package requested for disk '/home/esa/Downloads/PA-VM-KVM-10.2.9-h1.qcow2'
  critical   1730818372 failed gleaning source data from disk '/home/esa/Downloads/PA-VM-KVM-10.2.9-h1.qcow2'
  critical   1730818372 error allocating disks for packaging: inspectionError: failed gleaning source data from disk '/home/esa/Downloads/PA-VM-KVM-10.2.9-h1.qcow2'
    🆘 finished unsuccessfully in 0 seconds
inspectionError: failed gleaning source data from disk '/home/esa/Downloads/PA-VM-KVM-10.2.9-h1.qcow2'
```

"failed gleaning source data from disk" doesn't really tell what's going on. 

Turns out:
- At first I had just misspelled the path to a file (a "file not found" would have been nice)
- Then my file name failed to satisfy the regex in https://github.com/carlmontanari/boxen/blob/main/boxen/platforms/util.go#L10C6-L10C29
- Then my file name (now restored to the original vendor download: `PA-VM-KVM-10.2.9-h1.qcow2`) failed to satisfy the regex in https://github.com/carlmontanari/boxen/blob/main/boxen/platforms/util.go#L69

I find two things here counteractive to the claim:
> Key Features:
> Easy: It's easy to get going with boxen -- grab your network operating systems qcow2 disk and point boxen to it!

- README should mention that not just any qcow2 file will do, but that it has to have a specific name (maybe failing to parse the -h1 from Palo Alto is a bug/missing feature though?)

- It would be nice to have an indication of what is wrong that doesn't require the user to download sources and install delve to step through the code to see where things go wrong leading to a generic error message. Here the root cause seems to be that the error handler in https://github.com/carlmontanari/boxen/blob/main/boxen/boxen/common.go#L105-L116 checks for `err != nil` and then just ignores the contents entirely causing multiple different error sources to be mixed into one

**Comment by henriots** [comment]
Created a PR that should fix this issue Fix panos #49 
Tested with image ``PA-VM-KVM-10.2.10-h12.qcow2``

**Comment by fbouzemarene** [comment]
it seems i've been hit by the same issue trying to box check point Cloudguard new R82 qcow2 disk 

![Image](https://github.com/user-attachments/assets/5de8adf9-3d5b-41fb-ae9b-b7c57d4149e4)

**Comment by littlewing7** [comment]
Hi, same problem and rename the qcow2 original file from `jaguar_opt_main-777-991001696_unsecured.qcow2`  to: `Check_Point_R82_Cloudguard_KVM_all_deployment_unsecured.qcow2` doesn't solve the problem. 

`cp -p R82/jaguar_opt_main-777-991001696_unsecured.qcow2 R82/Check_Point_R82_Cloudguard_KVM_all_deployment_unsecured.qcow2`
`cd R82
`
`sudo /MMA/boxen/bin/boxen package --disk `Check_Point_R82_Cloudguard_KVM_all_deployment_unsecured.qcow2`

return this: 

`sudo /MMA/boxen/bin/boxen package --disk Check_Point_R82_Cloudguard_KVM_all_deployment_unsecured.qcow2`
`      info   1752217850 package requested for disk Check_Point_R82_Cloudguard_KVM_all_deployment_unsecured.qcow2`
`  critical   1752217850 failed gleaning source data from disk Check_Point_R82_Cloudguard_KVM_all_deployment_unsecured.qcow2`
`  critical   1752217850 error allocating disks for packaging: inspectionError: failed gleaning source data from disk Check_Point_R82_Cloudguard_KVM_all_deployment_unsecured.qcow2`
`        🆘 finished unsuccessfully in 0 seconds `
`inspectionError: failed gleaning source data from disk 'Check_Point_R82_Cloudguard_KVM_all_deployment_unsecured.qcow2`


seems that the qcow2 file inside contain the original file name? possible ? 

How can I fix ?

Max

**Comment by henriots** [comment]
Unfortunately, I have never used nor have access to Check Point VMs. If I have time, I could take a look

**Comment by littlewing7** [comment]
I apologise,  I missing your kindly reply. 

If you want I can provide you the Check Point Cloudguard .img of R81.20  and R82 (is very large .cow2 files:  4/5 Gbyte)

BTW: can you please explain or point me in the right direction to understand how this tool (boxen) work to understand which is the changes made to the original .cow2 image (what exactly change ? from the original and the produced new image output?)

cheers
Massimo
